products:
  -
      id: 1
      image: { src:"product_mini_1.jpg", alt:"", class:"imgm img-thumbnail"}
      name: T-shirt délavé à manches courtes
      reference: "demo_1"
      category: "T-shirts"
      base_price: 16.510000
      final_price: 19.81
      quantity: 1799
      status: 0
      position: 0
  -
      id: 3
      image: { src:"product_mini_8.jpg", alt:"", class:"imgm img-thumbnail"}
      name: "Robe imprimée"
      reference: "demo_3"
      category: "Robes décontractées"
      base_price: 25.999852
      final_price: 31.2
      quantity: 899
      status: 0
      position: 2
  -
      id: 4
      image: { src:"product_mini_10.jpg", alt:"", class:"imgm img-thumbnail"}
      name: "Robe imprimée"
      reference: "demo_4"
      category: "Robes de soirée"
      base_price: 50.994153
      final_price: 61.19
      quantity: 900
      status: 0
      position: 3
  -
      id: 5
      image: { src:"product_mini_12.jpg", alt:"", class:"imgm img-thumbnail"}
      name: "Robe d'été imprimée"
      reference: "demo_5"
      category: "Robes d'été"
      base_price: 30.506321
      final_price: 34.78
      quantity: 3600
      status: 0
      position: 4
  -
      id: 6
      image: { src:"product_mini_16.jpg", alt:"", class:"imgm img-thumbnail"}
      name: "Robe d'été imprimée"
      reference: "demo_6"
      category: "Robes d'été"
      base_price: 30.502569
      final_price: 36.6
      quantity: 900
      status: 0
      position: 5
  -
      id: 7
      image: { src:"product_mini_20.jpg", alt:"", class:"imgm img-thumbnail"}
      name: "Robe en mousseline imprimée"
      reference: "demo_7"
      category: "Robes d'été"
      base_price: 20.501236
      final_price: 19.68
      quantity: 1800
      status: 0
      position: 6
  -
      id: 2
      image: { src:"product_mini_7.jpg", alt:"", class:"imgm img-thumbnail"}
      name: Chemisier
      reference: "demo_2"
      category: "Chemisiers"
      base_price: 26.999852
      final_price: 32.4
      quantity: 1799
      status: 0
      position: 1
